#
# Composes records from the (slightly edited) study plan text version
# input/study_plan.txt --> compose_output/composed_plan.txt
#
# Expected output record format generated by compose
# nn::code::description::credits[2345](::req)*::(bsc|dipl)::(nivel|_)::(ciclo|_)
# req ~ EI(F|G)...O? | LIX...
#
# To run
# awk -f compose.awk input/study_plan.txt > compose_output/composed_plan.txt

# 1) Nombre: ANDRES GUTIERREZ ARCIA ID:402310453 correo: andres.gutierrez.arcia@gmail.com HORARIO: 01 pm
# 2) Nombre: ADRIAN PRENDAS ARAYA ID:604140420 correo: a6r2an@gmail.com HORARIO: 01 pm
# 3) Nombre: CARLOS MURILLO BADILLA ID:402360192 correo: cmb2897@gmail.com HORARIO: 01 pm
# 4) Nombre: JOAQUÍN ALEJANDRO SÁNCHEZ BARBOZA ID:114160575 correo: j.alejandro.1290@gmail.com HORARIO: 01 pm
#

BEGIN {
	#RS = "\r\n\r\n";  # Record separator
	#FS = "\r\n";      # Field separator

	RS = "\n\n";
	FS = "\n";

	OFS = "::"; 		 # Output field separator
	nn = 1;
	grado = "dipl";
	nivel = "";
	ciclo = "";
	start = 0;
	saved = 0;
	code = "";
}

/Nivel/{
	nivel = $1;
}
/Ciclo/{
	ciclo = $1;
}
/DIPLOMADO/{
	grado = "bsc";
}
/EIF|EIG|MAY|LIX|Optativa|Estudios/{
	start = 1;
	saved = 0;
	if(code == ""){
		code = $0;
		gsub(" ", "", code);
		gsub("-", "", code);
		gsub("EstudiosGenerales", "Estudios Generales ", code);
	}
}
/^\s+$/{
	if(start == 1 && saved == 0){
		# Aqui es donde voy a salvar el curso en un array
		cursos
		nn++;
		saved = 1;
		code = "";
	}
}
END{
	print nn;
}
