#
# Composes records from the (slightly edited) study plan text version
# input/study_plan.txt --> compose_output/composed_plan.txt
#
# Expected output record format generated by compose
# nn::code::description::credits[2345](::req)*::(bsc|dipl)::(nivel|_)::(ciclo|_)
# req ~ EI(F|G)...O? | LIX...
#
# To run
# awk -f compose.awk input/study_plan.txt > compose_output/composed_plan.txt

# 1) Nombre: ANDRES GUTIERREZ ARCIA ID:402310453 correo: andres.gutierrez.arcia@gmail.com HORARIO: 01 pm
# 2) Nombre: ADRIAN PRENDAS ARAYA ID:604140420 correo: a6r2an@gmail.com HORARIO: 01 pm
# 3) Nombre: CARLOS MURILLO BADILLA ID:402360192 correo: cmb2897@gmail.com HORARIO: 01 pm
# 4) Nombre: JOAQUÍN ALEJANDRO SÁNCHEZ BARBOZA ID:114160575 correo: j.alejandro.1290@gmail.com HORARIO: 01 pm
#


BEGIN { 
	RS = "\r\n\r\n"  # Record separator
	FS = "\r\n"      # Field separator
	OFS = "::" 		 # Output field separator
	nn = 1
	grado = "dipl"
	nivel = ""
	ciclo = ""
}

/Nivel/{ #/^(I{1,3}|IV) Nivel/   #FS !~ /\s*/

	split($0,arr," ") 	# [1]="I"  [2]="Ciclo/Nivel"
	nivel = arr[1]  	# array start at 1 ??¿¿
	opt[i++] = arr[1]   # Uso ese array con {I,II,III,IV} para las optativas
}

/Ciclo/{ #/^(I{1,3}|IV) Ciclo/   #FS !~ /\s*/

	split($0,arr," ") 	# [1]="I"  [2]="Ciclo/Nivel"
	ciclo = arr[1]  	# array start at 1 ??¿¿
}

/^DIPLOMADO/{ # after dipl -> bsc
	grado = "bsc" 
}

/^BACHILLERATO/{
	ciclo=nivel="_"
}

/^(EIF|EIG|MAY|LIX|Optativa|Estudios)/{

	if($0 ~ /Estudios/ || /Optativa/){
		$4 = "Admission"
		$3 = $2
		$2 = $1
		
		gsub(" ", "", $1)
		
			if($0 ~ /Optativa/){
				$1 = $1opt[cont++] # Guardo los niveles y luego los reutilizo como numerax para Optativa
			}
	}
	 
	 gsub(" ", "", $1) # Cuidado con el orden
	 if($1 ~ /EI(F|G)[0-9][0-9][0-9]O/){	#Optativas
		if(NF == 2){
			$3 = 3
			$4 = "Admission"
		}
		
		else if(NF >= 3){
			var1 = $3
			$3 = 3
			
			gsub(" ", "", var1)
			
			if(NF == 4){
				var2 = $4
				gsub(" ", "", var2)
				if(var2 ~ /EIF\s*[0-9]{3}/ || /MAY\s*[0-9]{3}/){ #Respetar este orden
					$5 = substr(var2, 1, 6)
				}
			}
			
			if($1 == "EIG416O"){ 
				$4 = substr(var1, 9, 7)
			}
			
			else if(var1 ~ /EIF\s*[0-9]{3}/){ #Respetar este orden
				$4 = substr(var1, 1, 6)
			}
			
			else if(var1 ~ /EIF\s*[0-9]{3}O/){ # De lo contrario se anulan.
				$4 = substr(var1, 1, 7)
			}
			
		}
	}
	 
	 gsub("-", "", $0)
	 gsub("\r\n", "::", $0)
	 gsub("Ingreso a Carrera", "Admission", $0)

	print nn++, $0, grado, nivel, ciclo			
}
