#
# Composes records from the (slightly edited) study plan text version
# loriacarlos@gmail.com
# input/study_plan.txt --> compose_output/composed_plan.txt
#
# Expected output record format generated by compose
# nn::code::description::credits[2345](::req)*::(bsc|dipl)::(level|_)::(cycle|_)
# req ~ EI(F|G)...O? | LIX...
#
# To run
# awk -f compose.awk input/study_plan.txt > compose_output/composed_plan.txt


BEGIN { 
	nn = 0;
	code = "";
	description = "";
	credits = 0;
	req = "";
	title = "";
	level = "";
	cyle = "";
	SR = "/r/n";

}

{
	if($2 =="Nivel"){
		level = $1;
	}
	if($2 =="Ciclo"){
		cycle = $1;
	}
	if($0 == "Ingreso a Carrera"){
		req = $0
	}

}

/^(EIF|MAY|LIX)\-?\s?[0-9]{3}/{
	code = $0
	print nn++,$0
}

/^[0-9]+/{
	credits = $0
}

{
	#print $0
	#print nn++"::"code"::"description"::"credits"::"req"::"title"::"level"::"cycle
}


END {}

