# Generates graphviz file from the compose.awk output
# loriacarlos@gmail.com
# compose_output/composed_plan.txt --> gv_output/study_plan.gv
# To run
# awk -f gengraph.awk compose_output/composed_plan.txt > gv_output/study_plan.gv
# Expected input record format generated by compose
# nn::code::description::[2345](::req)*::(bsc|dipl)::(level|_)::(cycle|_)
BEGIN{
	FS="::"
	printf "digraph G { \n"
	printf "ranksep=.75 size = \"10.5,7.5\";"
}
	function curso(columna,current){ # col  6
		if ($columna ~ /(dipl|bsc)/) {
			return
		}else{
			#entonces es un requisito
			#printf "nivel %s ciclo %s ", $NF, $(NF-1)
			printf "%s -> %s;\n" ,$columna ,$current
			#printf "{rank = same; \"%s\"; \"%s\"}", $NF, $(NF-1)
			columna = columna + 1
			curso(columna, current)
		}
		return
}
{
	columnaDef = 5
	current = 2
	curso(columnaDef,current)

	if($2 ~ /^(MAY|MATEMATICA)/){
		printf "%s [shape=box, style=filled, color=yellow]", $2
		#printf "%s [shape=box, style=filled, color=yellow]", "MATEMATICA"
	}

	if($2 ~ /^(EIF|CURSOS_CARRERA)/){
		printf "%s [shape=box, style=filled, color=blue fontcolor=white]", $2
		#printf "%s [shape=box, style=filled, color=blue fontcolor=white]", "CURSOS_CARRERA"
	}
	if($2 ~ /^(LIX|INGLES)/){
		printf "%s [shape=box, style=filled, color=red fontcolor=white]", $2
		#printf "%s [shape=box, style=filled, color=red fontcolor=white]", "INGLES"
	}
	if($2 ~ /^(EIG|CURSOS_EIGS)/){
		printf "%s [shape=box, style=filled, color=\"#02FF6C\"]", $2
		#printf "%s [shape=box, style=filled, color=\"#02FF6C\"]", "CURSOS_EIGS"
	}
	if($2 ~ /^(Optativa|OPTATIVOS)/){
		printf "%s [shape=box, style=filled, color=orange]", $2
		#printf "%s [shape=box, style=filled, color=orange]", "OPTATIVOS"
	}
	if($2 ~ /^(EstudiosGenerales|CURSOS_GENERALES)/){
		printf "%s [shape=box, style=filled, color=gray]", $2
		#printf "%s [shape=box, style=filled, color=gray]", "CURSOS_GENERALES"
	}
}

END{

	#printf "%s -> %s;\n" ,"CURSOS_CARRERA" ,"OPTATIVOS"
	#printf "%s -> %s;\n" ,"OPTATIVOS" ,"CURSOS_EIGS"
	#printf "%s -> %s;\n" ,"CURSOS_EIGS" ,"MATEMATICA"
	#printf "%s -> %s;\n" ,"MATEMATICA" ,"INGLES"
	#printf "%s -> %s;\n" ,"INGLES" ,"CURSOS_GENERALES"

	printf "{rank = same; \"Admission\"; \"Start\"}"
	printf "{rank = same; \"EIF200\"; \"I_I\"}"
	printf "Admission [shape=invhouse,sides=8,peripheries=3,color=\"#7DE802\",style=filled]"
	print "}"
}
