# Generates graphviz file from the compose.awk output
# loriacarlos@gmail.com
# compose_output/composed_plan.txt --> gv_output/study_plan.gv
# To run
# awk -f gengraph.awk compose_output/composed_plan.txt > gv_output/study_plan.gv
# Expected input record format generated by compose
# nn::code::description::[2345](::req)*::(bsc|dipl)::(level|_)::(cycle|_)
BEGIN{
	FS="::"
	printf "digraph G { \n"
	printf "ranksep=.95 size = \"5.5,5.5\";"
	{
		printf "node [shape=box, fontsize=16, style=filled, nodesep=.70, color=\"#FCC37C\"];"
		printf "START -> I_I -> I_II -> II_I -> II_II -> III_I -> III_II -> IV_I -> IV_II -> end;"
	}
}
	function curso(columna,current){
		if ($columna ~ /(dipl|bsc)/ || $columna ~ /(MAY)/) {
			return
		}else{
			printf "%s -> %s;\n" ,$columna ,$current
			if(!($NF ~ /_/)){
				printf "{rank = same; %s_%s; %s}", $(NF-1), $NF,$current

			}
			columna = columna + 1
			curso(columna, current)
		}
		return
}
$2 ~/^(EIF|EIG|Optativa)/{
	columnaDef = 5
	current = 2
	curso(columnaDef,current)
  printf "%s [shape=box, style=filled,nodesep=.70, color=\"#204260\" fontcolor=white]", $2

  if($2 ~ /^(Optativa)/){
		printf "%s [shape=box, style=filled, nodesep=.70,color=orange]", $2
	}

	if($(NF-2) ~ /^(dipl)/){
		printf "%s -> \"DIPLOMADO\"", $2
		printf "\"DIPLOMADO\" [shape=box, fontsize=16, style=filled, nodesep=.70,  fontcolor=white, color=\"#9E6534\"];"
		printf "edge [ color=\"#9E6534\"];"
	}else{
		printf "%s -> \"BACHILLERATO\"", $2
		printf "\"BACHILLERATO\" [shape=box, fontsize=16, style=filled, nodesep=.70, fontcolor=white,  color=\"#8C2B3D\"];"
		printf "edge [color=\"#8C2B3D\"];"
	}



}

END{
	printf "Admission [shape=invhouse,sides=8,peripheries=3,color=\"#7DE802\",style=filled]"
	print "}"
}
