# Generates graphviz file from the compose.awk output
# loriacarlos@gmail.com
# compose_output/composed_plan.txt --> gv_output/study_plan.gv
# To run
# awk -f gengraph.awk compose_output/composed_plan.txt > gv_output/study_plan.gv
BEGIN{
	
}
# Expected input record format generated by compose
# nn::code::description::[2345](::req)*::(bsc|dipl)::(level|_)::(cycle|_)


END{
	
	
}
