# Generates prolog file from compose.awk output
# loriacarlos@gmail.com
# compose_output/composed_plan.txt --> prolog_output/study_plan.pl
# To run
# awk -f src/prolog.awk output/composed_plan.txt > prolog_output/study_plan.pl
BEGIN {
	
}
# Expected input record format generated by compose
# nn::code::description::credits[2345](::req)*::(bsc|dipl)::(level|_)::(cycle|_)
# req ~ EI(F|G)...O? | LIX...


}
END{
}
